# Generated by Django 4.1.3 on 2022-11-11 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_personlist_person_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='list',
        ),
        migrations.DeleteModel(
            name='personList',
        ),
    ]
