# Generated by Django 4.1.3 on 2023-03-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_remove_person_list_delete_personlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='rep_exe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exe_id', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=30)),
                ('rep', models.CharField(max_length=30)),
            ],
        ),
    ]
